name: Deployment

on:
  push:
    branches: [ production ]
  
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: canvas
        run: sudo apt-get install libcairo2-dev libjpeg-dev libgif-dev

  deploy:
    name: Deploy to App Engine
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build # will run `yarn build` command
      - name: Google App Engine
        uses: google-github-actions/deploy-appengine@v0.4.0
        with:
          project_id: ${{secrets.GCP_PROJECT}}
          version: v1
          credentials: ${{secrets.GCP_CREDENTIALS}}
          deliverables: app.yaml
